export const LANGUAGES = [
  { code: "auto", name: "Auto Detect", flag: "un" },
  { code: "en", name: "English", flag: "gb" },
  { code: "es", name: "Spanish", flag: "es" },
  { code: "fr", name: "French", flag: "fr" },
  { code: "de", name: "German", flag: "de" },
  { code: "it", name: "Italian", flag: "it" },
  { code: "pt", name: "Portuguese", flag: "pt" },
  { code: "nl", name: "Dutch", flag: "nl" },
  { code: "ru", name: "Russian", flag: "ru" },
  { code: "zh", name: "Chinese (Simplified)", flag: "cn" },
  { code: "ja", name: "Japanese", flag: "jp" },
  { code: "ko", name: "Korean", flag: "kr" },
  { code: "ar", name: "Arabic", flag: "sa" },
  { code: "hi", name: "Hindi", flag: "in" },
  { code: "bn", name: "Bengali", flag: "bd" },
  { code: "ur", name: "Urdu", flag: "pk" },
  { code: "pa", name: "Punjabi", flag: "in" },
  { code: "mr", name: "Marathi", flag: "in" },
  { code: "te", name: "Telugu", flag: "in" },
  { code: "ta", name: "Tamil", flag: "in" },
  { code: "gu", name: "Gujarati", flag: "in" },
  { code: "tr", name: "Turkish", flag: "tr" },
  { code: "pl", name: "Polish", flag: "pl" },
  { code: "vi", name: "Vietnamese", flag: "vn" },
  { code: "th", name: "Thai", flag: "th" },
  { code: "id", name: "Indonesian", flag: "id" },
  { code: "ms", name: "Malay", flag: "my" },
  { code: "tl", name: "Tagalog", flag: "ph" },
  { code: "fa", name: "Persian", flag: "ir" },
  { code: "sw", name: "Swahili", flag: "ke" },
  { code: "uk", name: "Ukrainian", flag: "ua" },
  { code: "el", name: "Greek", flag: "gr" },
  { code: "he", name: "Hebrew", flag: "il" },
  { code: "ro", name: "Romanian", flag: "ro" }
];